services:
  api:
    image: chatroom-dev
    build:
      context: .
      dockerfile: ./chatroom-back/Chat.Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80; #https://+:443
      - ConnectionStrings__Database=Host=db;Port=5432;Database=chatroom;Username=chatdbuser;Password=myverysecurepassword
    ports:
      - "7293:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=chatdbuser
      - POSTGRES_PASSWORD=myverysecurepassword
    shm_size: 128mb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: